### ISSUE TITLE
Gnuplot's podo theme appears to be identical to Okabe and Ito

### ISSUE THREAD

**Issue by Stratus3D** [ahrendsen/colorblind#1]
Gnuplot 5's `podo` theme appears to be identical to Okabe and Ito's recommended colors. Is this something that should be noted in the readme? Or is there a subtle difference between the two that I missed?

**Comment by ahrendsen** [comment]
Yep! The readme should be updated to add note about the new features introduced in gnuplot version 5.0 to easily globally set a colorblind friendly palette.

**Comment by Stratus3D** [comment]
Took a stab at this, feel free to edit or close it if it is not what you had in mind: https://github.com/ahrendsen/colorblind/pull/2

**Comment by ahrendsen** [comment]
Fixed by #2.

Looks great! Thanks so much.
